<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/28 10:31:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=flip',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
