<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/27 16:16:02
sfConfig::add(array(
  'app_facebook_apiKey' => 'e7474f12247c43b42abc25d296d3b4a2',
  'app_facebook_appSecret' => 'd343f8e8ed5960218bec36ef4cf70233',
  'app_facebook_appId' => '112001728817137',
));
