<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/03/27 16:16:03
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'swift_doctrinespool' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfwidgetformdoctrinechoice' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinecli' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfformfilterdoctrine' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfdoctrinerecord' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinegenerator' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformgenerator' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinedataloadtask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebuildtask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinebuildformstask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinedatadumptask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildschematask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinedropdbtask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinemigratetask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebasetask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinedqltask' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinepager' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineroute' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfvalidatordoctrineunique' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrineexception' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sftesterdoctrine' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrineconnectionprofiler' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',

  // project
  'basefacebookuserformfilter' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/filter/doctrine/base/BaseFacebookUserFormFilter.class.php',
  'baseflipfacebookuserformfilter' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/filter/doctrine/base/BaseFlipFacebookUserFormFilter.class.php',
  'flipfacebookuserformfilter' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/filter/doctrine/FlipFacebookUserFormFilter.class.php',
  'facebookuserformfilter' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/filter/doctrine/FacebookUserFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'baseflipfacebookuserform' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/form/doctrine/base/BaseFlipFacebookUserForm.class.php',
  'basefacebookuserform' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/form/doctrine/base/BaseFacebookUserForm.class.php',
  'baseformdoctrine' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/form/doctrine/BaseFormDoctrine.class.php',
  'flipfacebookuserform' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/form/doctrine/FlipFacebookUserForm.class.php',
  'facebookuserform' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/form/doctrine/FacebookUserForm.class.php',
  'baseform' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/form/BaseForm.class.php',
  'facebookmobile' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/facebook_mobile.php',
  'facebook' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/facebook.php',
  'facebookdesktop' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/facebook_desktop.php',
  'facebookrestclient' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/facebookapi_php5_restlib.php',
  'facebookrestclientexception' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/facebookapi_php5_restlib.php',
  'facebookapierrorcodes' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/facebookapi_php5_restlib.php',
  'services_json' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/jsonwrapper/JSON/JSON.php',
  'services_json_error' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/facebook/jsonwrapper/JSON/JSON.php',

  // project_model
  'flipfacebookusertable' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/model/doctrine/FlipFacebookUserTable.class.php',
  'baseflipfacebookuser' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/model/doctrine/base/BaseFlipFacebookUser.class.php',
  'flipfacebookuser' => '/home/kevin/projects/FLIP-django-facebook/frontend/lib/model/doctrine/FlipFacebookUser.class.php',

  // application
  'myuser' => '/home/kevin/projects/FLIP-django-facebook/frontend/apps/facebook/lib/myUser.class.php',

  // modules
);
