<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/27 16:16:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=flip',
  'username' => 'flip',
  'password' => 'r65wew7XpwL',
  'name' => 'doctrine',
)),);
