<?php

/**
 * BaseFlipFacebookUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uid
 * @property timestamp $last_profile_update_at
 * @property string $session_key
 * @property timestamp $expiration_time
 * @property Rating $MyRatings
 * @property Rating $RatingsOfMe
 * @property Doctrine_Collection $MySkills
 * 
 * @method integer             getUid()                    Returns the current record's "uid" value
 * @method timestamp           getLastProfileUpdateAt()    Returns the current record's "last_profile_update_at" value
 * @method string              getSessionKey()             Returns the current record's "session_key" value
 * @method timestamp           getExpirationTime()         Returns the current record's "expiration_time" value
 * @method Rating              getMyRatings()              Returns the current record's "MyRatings" value
 * @method Rating              getRatingsOfMe()            Returns the current record's "RatingsOfMe" value
 * @method Doctrine_Collection getMySkills()               Returns the current record's "MySkills" collection
 * @method FlipFacebookUser    setUid()                    Sets the current record's "uid" value
 * @method FlipFacebookUser    setLastProfileUpdateAt()    Sets the current record's "last_profile_update_at" value
 * @method FlipFacebookUser    setSessionKey()             Sets the current record's "session_key" value
 * @method FlipFacebookUser    setExpirationTime()         Sets the current record's "expiration_time" value
 * @method FlipFacebookUser    setMyRatings()              Sets the current record's "MyRatings" value
 * @method FlipFacebookUser    setRatingsOfMe()            Sets the current record's "RatingsOfMe" value
 * @method FlipFacebookUser    setMySkills()               Sets the current record's "MySkills" collection
 * 
 * @package    flip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseFlipFacebookUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('flip_facebook_user');
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('last_profile_update_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('session_key', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('expiration_time', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Rating as MyRatings', array(
             'local' => 'uid',
             'foreign' => 'uid'));

        $this->hasOne('Rating as RatingsOfMe', array(
             'local' => 'uid',
             'foreign' => 'by_uid'));

        $this->hasMany('MySkills', array(
             'local' => 'uid',
             'foreign' => 'uid'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}