<?php

/**
 * BaseRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uid
 * @property integer $by_uid
 * @property integer $skill_id
 * @property enum $rating
 * @property Skill $Skill
 * @property Doctrine_Collection $RatedUser
 * @property Doctrine_Collection $RatingUser
 * 
 * @method integer             getUid()        Returns the current record's "uid" value
 * @method integer             getByUid()      Returns the current record's "by_uid" value
 * @method integer             getSkillId()    Returns the current record's "skill_id" value
 * @method enum                getRating()     Returns the current record's "rating" value
 * @method Skill               getSkill()      Returns the current record's "Skill" value
 * @method Doctrine_Collection getRatedUser()  Returns the current record's "RatedUser" collection
 * @method Doctrine_Collection getRatingUser() Returns the current record's "RatingUser" collection
 * @method Rating              setUid()        Sets the current record's "uid" value
 * @method Rating              setByUid()      Sets the current record's "by_uid" value
 * @method Rating              setSkillId()    Sets the current record's "skill_id" value
 * @method Rating              setRating()     Sets the current record's "rating" value
 * @method Rating              setSkill()      Sets the current record's "Skill" value
 * @method Rating              setRatedUser()  Sets the current record's "RatedUser" collection
 * @method Rating              setRatingUser() Sets the current record's "RatingUser" collection
 * 
 * @package    flip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rating');
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('by_uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('skill_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rating', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Not very good',
              1 => 'Good',
              2 => 'Very good',
              3 => 'Excellent',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Skill', array(
             'local' => 'skill_id',
             'foreign' => 'id'));

        $this->hasMany('FlipFacebookUser as RatedUser', array(
             'local' => 'uid',
             'foreign' => 'uid'));

        $this->hasMany('FlipFacebookUser as RatingUser', array(
             'local' => 'by_uid',
             'foreign' => 'uid'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}