<?php

/**
 * BaseMySkills
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $uid
 * @property FlipFacebookUser $FlipFacebookUser
 * 
 * @method integer          getUid()              Returns the current record's "uid" value
 * @method FlipFacebookUser getFlipFacebookUser() Returns the current record's "FlipFacebookUser" value
 * @method MySkills         setUid()              Sets the current record's "uid" value
 * @method MySkills         setFlipFacebookUser() Sets the current record's "FlipFacebookUser" value
 * 
 * @package    flip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMySkills extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('my_skills');
        $this->hasColumn('uid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FlipFacebookUser', array(
             'local' => 'uid',
             'foreign' => 'uid'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}